-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.candidates
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    date_of_birth timestamp without time zone NOT NULL,
    national_id character varying(11) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.cities
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    city_name character varying(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.curriculum_vitaes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    candidate_id integer NOT NULL,
    photo character varying,
    github_link character varying(255),
    linked_link character varying(255),
    cover_letter character varying(255),
    cv_status boolean,
    PRIMARY KEY (id)
);

CREATE TABLE public.email_verificate_candidates
(
    id integer NOT NULL,
    candidate_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.email_verificate_employers
(
    id integer NOT NULL,
    employer_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.email_verificator
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    verification_code character varying(8) NOT NULL,
    is_verified boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    id integer NOT NULL,
    first_name character varying(30) NOT NULL,
    last_name character varying(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employer_activation
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    employer_id integer NOT NULL,
    employee_id integer NOT NULL,
    if_verificated boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    id integer NOT NULL,
    company_name character varying(100) NOT NULL,
    website_adress character varying(80) NOT NULL,
    phone_number character varying(15) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.foreign_languages
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    cv_id integer NOT NULL,
    language_level "char" NOT NULL,
    language_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_advertisement
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    job_titles_id integer NOT NULL,
    employer_id integer NOT NULL,
    city_id integer NOT NULL,
    job_explanation character varying(200) NOT NULL,
    min_wage integer,
    max_wage integer,
    amount_of_open_positions integer NOT NULL,
    application_deadline character varying(30),
    is_active boolean,
    created_date timestamp without time zone,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_experiences
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    cv_id integer NOT NULL,
    workplace_name character varying(50) NOT NULL,
    "position" character varying(50) NOT NULL,
    start_date date NOT NULL,
    end_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_titles
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    title character varying(60) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.languages
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    language_name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.schools
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    cv_id integer NOT NULL,
    school_name character varying NOT NULL,
    start_date date,
    graduate_date date,
    PRIMARY KEY (id)
);

CREATE TABLE public.technologies
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    cv_id integer NOT NULL,
    technology_name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(50) NOT NULL,
    password character varying(25) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.candidates
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.curriculum_vitaes
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.email_verificate_candidates
    ADD FOREIGN KEY (candidate_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.email_verificate_candidates
    ADD FOREIGN KEY (id)
    REFERENCES public.email_verificator (id)
    NOT VALID;


ALTER TABLE public.email_verificate_employers
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.email_verificate_employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.email_verificator
    ADD FOREIGN KEY (id)
    REFERENCES public.email_verificate_employers (id)
    NOT VALID;


ALTER TABLE public.email_verificator
    ADD FOREIGN KEY (id)
    REFERENCES public.email_verificate_candidates (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employer_activation
    ADD FOREIGN KEY (employee_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.employer_activation
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.foreign_languages
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.curriculum_vitaes (id)
    NOT VALID;


ALTER TABLE public.foreign_languages
    ADD FOREIGN KEY (language_id)
    REFERENCES public.languages (id)
    NOT VALID;


ALTER TABLE public.job_advertisement
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.job_advertisement
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.job_advertisement
    ADD FOREIGN KEY (job_titles_id)
    REFERENCES public.job_titles (id)
    NOT VALID;


ALTER TABLE public.job_experiences
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.curriculum_vitaes (id)
    NOT VALID;


ALTER TABLE public.schools
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.curriculum_vitaes (id)
    NOT VALID;


ALTER TABLE public.technologies
    ADD FOREIGN KEY (cv_id)
    REFERENCES public.curriculum_vitaes (id)
    NOT VALID;

END;
